/**
 * execute_code — LLM 生成 Node.js 代码并在子进程中执行
 *
 * 这是平台 LLM 大脑的核心能力：当现有 MCP 工具无法覆盖某个场景时，
 * LLM 可以自主编写 Node.js 脚本进行网络探测、数据分析、漏洞验证等。
 *
 * Node.js 天然支持 HTTP/TCP/UDP/DNS/Crypto/FS，无需额外安装。
 */
import { execFile } from 'node:child_process';
import { writeFile, unlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import os from 'node:os';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';

const MAX_OUTPUT_BYTES = 512 * 1024; // 512KB output limit
const DEFAULT_TIMEOUT_MS = 30_000;   // 30s default
const MAX_TIMEOUT_MS = 300_000;      // 5min max

interface ExecutionResult {
  exitCode: number | null;
  stdout: string;
  stderr: string;
  durationMs: number;
  truncated: boolean;
}

function runScript(scriptPath: string, timeoutMs: number, env?: Record<string, string>): Promise<ExecutionResult> {
  return new Promise((resolve) => {
    const startMs = Date.now();

    const child = execFile(
      process.execPath, // use current Node.js binary
      [scriptPath],
      {
        timeout: timeoutMs,
        maxBuffer: MAX_OUTPUT_BYTES,
        env: env ? { ...process.env, ...env } : process.env,
        windowsHide: true,
      },
      (error, stdout, stderr) => {
        const durationMs = Date.now() - startMs;
        let exitCode: number | null = null;
        let truncated = false;

        if (error) {
          if ('code' in error && error.code === 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER') {
            truncated = true;
          }
          if (error.killed) {
            stderr = `${stderr}\n[TIMEOUT] 脚本执行超时 (${timeoutMs}ms)`;
          }
          exitCode = 'code' in error && typeof (error as { code?: unknown }).code === 'number'
            ? (error as { code: number }).code
            : 1;
        }

        resolve({
          exitCode: exitCode ?? child.exitCode ?? 0,
          stdout: stdout.slice(0, MAX_OUTPUT_BYTES),
          stderr: stderr.slice(0, MAX_OUTPUT_BYTES / 4),
          durationMs,
          truncated,
        });
      },
    );
  });
}

export function registerExecuteCode(server: McpServer) {
  const platformHint = `[Runtime: Node.js ${process.version} on ${process.platform}/${process.arch}, tmpdir=${os.tmpdir()}]`;
  server.tool(
    'execute_code',
    `Execute Node.js code generated by the LLM. Supports HTTP, TCP, UDP, DNS, crypto, file I/O natively. Use this when no existing MCP tool covers the scenario. ${platformHint}`,
    {
      code: z.string().describe('Node.js code to execute. Can use require/import for built-in modules (net, http, https, dns, crypto, fs, child_process, etc.)'),
      description: z.string().describe('Brief description of what this code does and why'),
      timeout_seconds: z.number().optional().default(30).describe('Execution timeout in seconds (max 300)'),
      env: z.record(z.string()).optional().describe('Additional environment variables'),
    },
    async ({ code, description, timeout_seconds, env }) => {
      const timeoutMs = Math.min((timeout_seconds ?? 30) * 1000, MAX_TIMEOUT_MS);
      const scriptId = randomUUID().slice(0, 8);
      const scriptPath = join(tmpdir(), `llm-script-${scriptId}.js`);

      try {
        // Write the LLM-generated code to a temp file
        await writeFile(scriptPath, code, 'utf-8');

        // Execute in a child process
        const result = await runScript(scriptPath, timeoutMs, env);

        const lines: string[] = [
          `## 脚本执行结果`,
          `**目的**: ${description}`,
          `**耗时**: ${result.durationMs}ms`,
          `**退出码**: ${result.exitCode}`,
        ];

        if (result.truncated) {
          lines.push('**注意**: 输出已截断（超过 512KB）');
        }

        if (result.stdout.trim()) {
          lines.push('', '### stdout', '```', result.stdout.trim(), '```');
        }

        if (result.stderr.trim()) {
          lines.push('', '### stderr', '```', result.stderr.trim(), '```');
        }

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify({
                exitCode: result.exitCode,
                stdout: result.stdout.trim(),
                stderr: result.stderr.trim(),
                durationMs: result.durationMs,
                truncated: result.truncated,
                description,
              }, null, 2),
            },
          ],
        };
      } catch (error) {
        return {
          content: [
            {
              type: 'text' as const,
              text: `脚本执行异常: ${error instanceof Error ? error.message : String(error)}`,
            },
          ],
          isError: true,
        };
      } finally {
        unlink(scriptPath).catch(() => {});
      }
    },
  );
}
