import type {
  ApprovalRecord,
  AssetRecord,
  ControlSetting,
  EvidenceRecord,
  McpToolRecord,
  MetricCard,
  PolicyRecord,
  ProjectRecord,
  TaskRecord,
  TimelineStage,
} from "@/lib/prototype-types"

export const dashboardMetrics: MetricCard[] = [
  { label: "项目总数", value: "12", delta: "+2 本周", tone: "neutral" },
  { label: "运行中项目", value: "5", delta: "2 个待接管", tone: "info" },
  { label: "已发现资产", value: "428", delta: "+31 今日", tone: "success" },
  { label: "已确认问题", value: "14", delta: "3 个待复核", tone: "warning" },
  { label: "待审批动作", value: "6", delta: "2 个高风险", tone: "danger" },
]

export const projects: ProjectRecord[] = [
  {
    id: "proj-huayao",
    name: "华曜科技匿名外网面梳理",
    seed: "huayao.com",
    targetType: "domain",
    stage: "待验证项生成",
    status: "运行中",
    pendingApprovals: 2,
    lastUpdated: "今天 12:10",
    riskSummary: "发现 1 个高危候选登录入口",
  },
  {
    id: "proj-xingtu",
    name: "星图教育开放资产评估",
    seed: "portal.xingtuedu.cn",
    targetType: "url",
    stage: "发现与指纹识别",
    status: "运行中",
    pendingApprovals: 1,
    lastUpdated: "今天 10:22",
    riskSummary: "新增 2 个 API 入口待识别",
  },
  {
    id: "proj-yunlan",
    name: "云岚医械公网暴露面验证",
    seed: "203.107.18.0/24",
    targetType: "cidr",
    stage: "审批前排队",
    status: "已阻塞",
    pendingApprovals: 3,
    lastUpdated: "昨天 18:40",
    riskSummary: "3 个高风险动作等待审批",
  },
]

export const projectDetailSummary = {
  name: "华曜科技匿名外网面梳理",
  target: "huayao.com / admin.huayao.com",
  currentStage: "待验证项生成",
  status: "运行中",
  pendingApprovals: 2,
  riskSummary: "发现 1 个高危候选登录入口，1 个待确认 API 入口",
  lastUpdated: "今天 12:10",
  blockingReason: "2 个高风险验证项待审批，主路径暂停进入受控 PoC 验证。",
  nextStep: "优先处理管理后台与 API 入口审批，随后恢复受控验证。",
  reflowNotice: "发现新管理入口 admin.huayao.com，已回流至持续信息收集并补充前置任务。",
}

export const projectTimeline: TimelineStage[] = [
  { title: "授权与范围定义", state: "done", note: "授权说明与范围规则已锁定" },
  { title: "种子目标接收", state: "done", note: "域名与种子 URL 已标准化" },
  { title: "持续信息收集", state: "watching", note: "发现新管理入口，已回流补采" },
  { title: "目标关联与范围判定", state: "done", note: "新增子域已确认为授权范围内" },
  { title: "发现与指纹识别", state: "done", note: "识别到 nginx、Next.js 与管理入口特征" },
  { title: "待验证项生成", state: "current", note: "2 个高风险验证项等待人工判断" },
  { title: "审批前排队", state: "blocked", note: "审批通过后进入受控验证" },
]

export const projectTasks: TaskRecord[] = [
  {
    id: "task-01",
    title: "认证绕过验证候选单生成",
    status: "waiting_approval",
    reason: "等待“高风险受控验证”审批通过",
    priority: "P1",
  },
  {
    id: "task-02",
    title: "admin.huayao.com 归属确认",
    status: "waiting_dependency",
    reason: "依赖候选资产范围判定完成",
    priority: "P1",
  },
  {
    id: "task-03",
    title: "夜间被动情报刷新",
    status: "scheduled",
    reason: "已排入 23:30 调度窗口",
    priority: "P3",
  },
]

export const dashboardPriorities = [
  {
    title: "审批阻塞优先清理",
    detail: "华曜科技项目有 2 个高风险验证项待处理，已阻塞主路径进入受控 PoC 验证。",
    tone: "danger" as const,
  },
  {
    title: "新入口回流补采",
    detail: "发现 admin.huayao.com 与 assets.huayao.com，需补做范围判定和信息收集。",
    tone: "warning" as const,
  },
  {
    title: "MCP 工具异常需要巡检",
    detail: "capture-evidence 当前健康检查异常，影响证据截图链路。",
    tone: "info" as const,
  },
]

export const approvals: ApprovalRecord[] = [
  {
    id: "APR-20260326-014",
    projectName: "华曜科技匿名外网面梳理",
    target: "admin.huayao.com/login",
    actionType: "受控认证绕过验证",
    riskLevel: "高",
    rationale: "入口识别到旧版认证框架特征，存在历史高频问题线索",
    impact: "对登录入口发起受控验证请求",
    mcpCapability: "受控验证类",
    tool: "auth-guard-check",
    status: "待处理",
    parameterSummary: "登录入口只读校验，速率 1 req/s，最长 3 分钟，自动脱敏保存响应片段。",
    prerequisites: ["确认目标仍在授权范围内", "校验时间窗口在 14:00 之后", "启用 capture-evidence 记录链路"],
    stopCondition: "出现验证码升级、账户锁定迹象或命中告警页立即终止。",
    blockingImpact: "阻塞“认证绕过验证候选单生成”，项目主路径停在待验证项生成阶段。",
    queuePosition: 1,
    submittedAt: "今天 12:06",
  },
  {
    id: "APR-20260326-015",
    projectName: "云岚医械公网暴露面验证",
    target: "api.yunlanmed.com/v1",
    actionType: "敏感接口权限校验",
    riskLevel: "高",
    rationale: "API 文档暴露鉴权缺失线索，需受控验证",
    impact: "对匿名接口进行只读权限验证",
    mcpCapability: "受控验证类",
    tool: "api-scope-check",
    status: "待处理",
    parameterSummary: "仅执行 GET/HEAD 权限校验，不落库，不写入，不触发敏感业务状态变更。",
    prerequisites: ["完成接口归属确认", "启用只读模式", "并发限制为 1"],
    stopCondition: "接口返回 429、5xx 波动或命中敏感字段时自动停止。",
    blockingImpact: "阻塞云岚医械项目进入受控 PoC 验证与问题定级。",
    queuePosition: 2,
    submittedAt: "今天 11:24",
  },
  {
    id: "APR-20260326-012",
    projectName: "星图教育开放资产评估",
    target: "portal.xingtuedu.cn/graphql",
    actionType: "Schema 暴露验证",
    riskLevel: "中",
    rationale: "响应头暴露 GraphQL 特征，需判断 introspection 是否开启。",
    impact: "发起只读 introspection 探测",
    mcpCapability: "接口识别类",
    tool: "graphql-surface-check",
    status: "已延后",
    parameterSummary: "仅检查 schema 暴露与匿名 introspection，不提交 mutation。",
    prerequisites: ["等待项目负责人确认夜间窗口", "限制总请求数不超过 8"],
    stopCondition: "出现速率限制或匿名 introspection 被显式禁用即停止。",
    blockingImpact: "不阻塞主路径，但影响开放 API 风险判定完整度。",
    queuePosition: 5,
    submittedAt: "昨天 18:08",
  },
]

export const assets: AssetRecord[] = [
  {
    id: "asset-443",
    projectName: "华曜科技匿名外网面梳理",
    type: "service",
    label: "443/tcp",
    profile: "nginx 1.22 + Next.js 前端入口",
    scopeStatus: "已纳入",
    lastSeen: "今天 11:52",
    host: "admin.huayao.com",
    ownership: "华曜科技管理后台入口",
    confidence: "0.86",
    exposure: "对外可访问，关联登录入口与 dashboard 跳转线索。",
    linkedEvidenceId: "EV-20260326-009",
    linkedTaskTitle: "认证绕过验证候选单生成",
    issueLead: "疑似旧版统一认证组件暴露管理端能力。",
    relations: [
      {
        id: "asset-rel-001",
        label: "huayao.com",
        type: "domain",
        relation: "父域名",
        scopeStatus: "已纳入",
      },
      {
        id: "asset-rel-002",
        label: "admin.huayao.com/login",
        type: "entry",
        relation: "登录入口",
        scopeStatus: "已纳入",
      },
      {
        id: "asset-rel-003",
        label: "EV-20260326-009",
        type: "evidence",
        relation: "关联证据",
        scopeStatus: "已纳入",
      },
    ],
  },
  {
    id: "asset-22",
    projectName: "星图教育开放资产评估",
    type: "port",
    label: "22/tcp",
    profile: "OpenSSH 8.4 版本线索",
    scopeStatus: "已纳入",
    lastSeen: "今天 09:14",
    host: "ops.xingtuedu.cn",
    ownership: "运维跳板机候选入口",
    confidence: "0.72",
    exposure: "公网开放端口，握手信息可见 OpenSSH 8.4 线索。",
    linkedEvidenceId: "EV-20260326-011",
    linkedTaskTitle: "SSH 暴露面版本复核",
    issueLead: "需确认是否属于供应商运维节点，避免误入范围外目标。",
    relations: [
      {
        id: "asset-rel-004",
        label: "portal.xingtuedu.cn",
        type: "subdomain",
        relation: "同项目关联域名",
        scopeStatus: "已纳入",
      },
      {
        id: "asset-rel-005",
        label: "EV-20260326-011",
        type: "evidence",
        relation: "Banner 采样证据",
        scopeStatus: "已纳入",
      },
    ],
  },
  {
    id: "asset-api",
    projectName: "云岚医械公网暴露面验证",
    type: "api",
    label: "api.yunlanmed.com/v1",
    profile: "REST API，疑似使用 Spring Boot",
    scopeStatus: "待确认",
    lastSeen: "昨天 17:08",
    host: "api.yunlanmed.com",
    ownership: "云岚医械开放接口集群",
    confidence: "0.67",
    exposure: "匿名访问可见 OpenAPI 片段，部分路径返回统一 JSON 错误体。",
    linkedEvidenceId: "EV-20260326-010",
    linkedTaskTitle: "敏感接口权限校验",
    issueLead: "疑似存在匿名可访问只读接口，需审批后验证。",
    relations: [
      {
        id: "asset-rel-006",
        label: "swagger-ui",
        type: "entry",
        relation: "文档入口",
        scopeStatus: "待确认",
      },
      {
        id: "asset-rel-007",
        label: "APR-20260326-015",
        type: "approval",
        relation: "待审批动作",
        scopeStatus: "待确认",
      },
    ],
  },
  {
    id: "asset-rpa",
    projectName: "华曜科技匿名外网面梳理",
    type: "service",
    label: "assets.huayao.com",
    profile: "静态资源分发域名，疑似共用对象存储出口",
    scopeStatus: "待复核",
    lastSeen: "今天 12:18",
    host: "assets.huayao.com",
    ownership: "静态资源与附件出口",
    confidence: "0.61",
    exposure: "目录结构线索与主站一致，但归属尚未完全确认。",
    linkedEvidenceId: "EV-20260326-012",
    linkedTaskTitle: "新增子域归属与范围判定",
    issueLead: "若确认纳入，需要回流补采对象存储与附件访问控制。",
    relations: [
      {
        id: "asset-rel-008",
        label: "admin.huayao.com",
        type: "subdomain",
        relation: "同源关联",
        scopeStatus: "待复核",
      },
      {
        id: "asset-rel-009",
        label: "对象存储桶",
        type: "storage",
        relation: "疑似后端依赖",
        scopeStatus: "待复核",
      },
    ],
  },
]

export const evidenceRecords: EvidenceRecord[] = [
  {
    id: "EV-20260326-009",
    projectName: "华曜科技匿名外网面梳理",
    title: "后台登录页暴露管理端标识",
    source: "页面截图 + 302 响应链路",
    confidence: "0.78",
    conclusion: "待复核问题",
    linkedApprovalId: "APR-20260326-014",
    rawOutput: [
      "GET /login -> 302 /dashboard",
      "response header: x-powered-by=Next.js",
      "html title: 华曜科技统一管理平台",
    ],
    screenshotNote: "登录页顶部出现统一管理平台字样，右下角存在版本标识。",
    structuredSummary: [
      "确认存在后台入口，且匿名可抵达登录页。",
      "302 链路指向 dashboard，说明存在认证后管理界面。",
      "页面静态资源路径带有 legacy-auth 组件命名。",
    ],
    linkedTaskTitle: "认证绕过验证候选单生成",
    linkedAssetLabel: "443/tcp",
    timeline: ["11:38 发现新入口", "11:42 页面截图采集完成", "11:46 响应链路结构化解析完成", "12:06 提交审批"],
    verdict: "需要审批通过后继续受控认证验证，暂不直接下结论。",
  },
  {
    id: "EV-20260326-010",
    projectName: "云岚医械公网暴露面验证",
    title: "开放 API 文档片段泄露鉴权结构",
    source: "OpenAPI JSON 片段 + 错误响应采样",
    confidence: "0.74",
    conclusion: "待复核问题",
    linkedApprovalId: "APR-20260326-015",
    rawOutput: [
      "GET /v1/openapi.json -> 200",
      "paths include /patient/export, /report/list",
      "anonymous GET /report/list -> 401 with business trace id",
    ],
    screenshotNote: "Swagger 文档页可匿名访问，接口分组暴露患者与报表域名词汇。",
    structuredSummary: [
      "文档入口匿名暴露，说明接口面结构可被直接枚举。",
      "错误响应包含业务 trace id，可辅助后续归因。",
      "高敏接口是否缺失鉴权仍需受控验证确认。",
    ],
    linkedTaskTitle: "敏感接口权限校验",
    linkedAssetLabel: "api.yunlanmed.com/v1",
    timeline: ["16:58 文档入口发现", "17:01 错误响应采样完成", "17:08 资产归档进入待确认", "11:24 提交审批"],
    verdict: "文档暴露已成立，但敏感接口权限缺失仍需审批后验证。",
  },
  {
    id: "EV-20260326-011",
    projectName: "星图教育开放资产评估",
    title: "SSH Banner 暴露版本信息",
    source: "Banner 抓取",
    confidence: "0.71",
    conclusion: "待复核问题",
    linkedApprovalId: "APR-20260326-012",
    rawOutput: ["SSH-2.0-OpenSSH_8.4", "cipher: curve25519-sha256", "host key: ecdsa-sha2-nistp256"],
    screenshotNote: "命令行截图显示端口开放与版本回显。",
    structuredSummary: [
      "公网端口直接返回 OpenSSH 版本线索。",
      "尚未确认是否属于供应商托管节点。",
      "需要结合归属结果决定是否继续版本风险校验。",
    ],
    linkedTaskTitle: "SSH 暴露面版本复核",
    linkedAssetLabel: "22/tcp",
    timeline: ["09:10 端口探测命中", "09:14 Banner 采样完成", "09:20 归属待确认"],
    verdict: "当前先做资产归属，避免对潜在非授权目标继续探测。",
  },
]

export const mcpTools: McpToolRecord[] = [
  {
    id: "mcp-01",
    capability: "目标解析类",
    toolName: "seed-normalizer",
    version: "1.4.2",
    riskLevel: "低",
    status: "启用",
    category: "输入标准化",
    defaultConcurrency: "8",
    rateLimit: "120 req/min",
    timeout: "15s",
    retry: "2 次",
    lastCheck: "今天 11:40",
  },
  {
    id: "mcp-02",
    capability: "受控验证类",
    toolName: "auth-guard-check",
    version: "2.3.0",
    riskLevel: "高",
    status: "启用",
    category: "认证验证",
    defaultConcurrency: "1",
    rateLimit: "12 req/min",
    timeout: "180s",
    retry: "0 次",
    lastCheck: "今天 12:02",
  },
  {
    id: "mcp-03",
    capability: "截图与证据采集类",
    toolName: "capture-evidence",
    version: "1.9.1",
    riskLevel: "中",
    status: "异常",
    category: "证据采集",
    defaultConcurrency: "3",
    rateLimit: "30 req/min",
    timeout: "45s",
    retry: "1 次",
    lastCheck: "今天 12:12",
  },
  {
    id: "mcp-04",
    capability: "接口识别类",
    toolName: "graphql-surface-check",
    version: "0.8.6",
    riskLevel: "中",
    status: "启用",
    category: "接口识别",
    defaultConcurrency: "2",
    rateLimit: "20 req/min",
    timeout: "60s",
    retry: "1 次",
    lastCheck: "昨天 23:18",
  },
]

export const systemControlOverview: ControlSetting[] = [
  {
    label: "默认并发",
    value: "项目级 3 / 高风险 1",
    description: "高风险动作始终串行，普通收集任务允许有限并发。",
    tone: "info",
  },
  {
    label: "默认速率",
    value: "被动 120 req/min / 验证 12 req/min",
    description: "严格限制主动验证速率，确保平台行为可审计可回溯。",
    tone: "success",
  },
  {
    label: "超时与重试",
    value: "45s / 1 次",
    description: "证据类工具允许一次自动重试，避免偶发网络波动造成误判。",
    tone: "warning",
  },
  {
    label: "紧急停止",
    value: "1 个异常工具待人工确认",
    description: "capture-evidence 健康异常，已切换到审慎模式。",
    tone: "danger",
  },
]

export const approvalPolicies: PolicyRecord[] = [
  {
    title: "高风险受控验证必须人工批准",
    description: "认证绕过、权限缺失、敏感数据导出类动作一律进入审批中心，不允许自动放行。",
    owner: "平台负责人",
    status: "生效中",
  },
  {
    title: "审批通过后 30 分钟内自动失效",
    description: "防止环境变化导致审批语境失真，超过窗口需要重新确认。",
    owner: "研究员",
    status: "生效中",
  },
  {
    title: "证据采集异常时禁止继续高风险动作",
    description: "当 capture-evidence 异常时，仅允许只读识别与归属判断，不进入受控 PoC。",
    owner: "系统策略",
    status: "已触发",
  },
]

export const scopeRules: PolicyRecord[] = [
  {
    title: "新增子域名默认进入待确认",
    description: "发现新子域后先判定归属，再决定是否回流到前置阶段任务。",
    owner: "项目流程",
    status: "启用",
  },
  {
    title: "供应商或第三方托管节点需要单独复核",
    description: "若归属存在第三方托管迹象，不自动纳入项目范围。",
    owner: "范围策略",
    status: "启用",
  },
  {
    title: "CIDR 范围外新增 IP 自动标记待复核",
    description: "即便由现有资产反查得到，也不直接视为授权资产。",
    owner: "范围策略",
    status: "启用",
  },
]
